.MODEL SMALL  
.STACK 100H
.DATA 
MSG1 DB 0DH,0AH,'ENTER A STRING WITH SPACES: $'
MSG2 DB 0DH,0AH,'IN EVERY WORD REVERSED IT WILL BE: $'

WRDCNTR DW 0

.CODE 
MAIN PROC
        MOV AX,@DATA      ;MOVING DATA TO DATA SEGMENT
        MOV DS,AX
        XOR CX,CX
        
        LEA DX,MSG1      ;PRINTING FIRST MESSAGE
        MOV AH,9
        INT 21H
        
        MOV AH,1        ;CHARACTER INPUT CODE
INPUT:

        INT 21H
        CMP AL,0DH      ;COMPARING WITH CARRIAGE RETURN
        JE PROCESS      ;IF EQUAL PROCESSING
        PUSH AX         ;PUSHING THE INPUT TO STACK
        INC CX          ;INCREASING COUNTER
        JMP INPUT       ;AGAIN TAKING INPUT
PROCESS:

        MOV BX,50H      ;MOVING 50H TO BX
        XCHG BX,SP      ;SWAPING STACK POINTER NOW THE SP IS POINTING TO A NEW ADDRESS
        
        PUSH 0020H      ;PUSHING SPACE TO THAT ADDRESS
        XCHG BX,SP      ;AGAING SWAPING SP TO ITS ACTUAL LOCATION
        INC WRDCNTR     ;INCREASING WORD COUNTER
    
NEWSTACK:               ;IMPLEMENTING A NEW STACK TO ANOTHER LOCATION
    
        POP DX          ;POPPING DATA FROM EXACT LOCATION AND KEEPING IN DX
        XCHG SP,BX      ;SWAPING STACK POINTER TO ANOTHER STACK
        PUSH DX         ;PUSHING THE POPPED DATA TO THAT LOCATION
        XCHG SP,BX      ;AGAING POINTING THE SP TO EXACT ADDRESS
        INC WRDCNTR     ;INCREASING WRDCNTR
        LOOP NEWSTACK   ;DOING UNTILL CX=0
    
PRINTPROCESS:

        MOV AH,9
        LEA DX,MSG2     ;PRINTING MESSAGE 2
        INT 21H
        
        MOV CX,WRDCNTR  ;SETTING THE LOOP COUNTER
        MOV WRDCNTR,0   ;MAKING WORD COUNTER 0
        
       
        PUSH 0020H      ;NOW THE STACK IS LOCATING TO NULL AND PUSHING A SPACE TO STACK
        INC WRDCNTR     ;INCREASING WRDCNTR
    
CHECKANDPRINT:

        XCHG SP,BX      ;NOW SWAPING AND POINTING TO THE ANOTHER STACK ADDRESS
        POP DX          ;POPPING FROM THAT STACK
        XCHG SP,BX      ;AND AGAING POINTING TO THE EXACT STACK
        
        CMP DL,20H      ;NOW COMPARING THE POPPED DATA WITH SPACE
        JNE NOPRINT     ;IF IT IS A SPACE THAT MEANS A WORD COMPLETES IF NOT NO PRINT
        MOV AH,2        
PRINT:
        POP DX          ;ELSE POP FROM THE ACTUAL STACK
        INT 21H         ;PRINTING IT
        DEC WRDCNTR
        JNZ PRINT       ;UNTILL WRDCNTR 0 PRINTING
        
    
        PUSH 0020H      ;AGAING PUSHING A SPACE INTO THE STACK BECAUSE THE STACK IS NOW EMPTY
NOPRINT:            
        PUSH DX         ;MAKING A WORD IN THE STACK
        INC WRDCNTR
        LOOP CHECKANDPRINT  ;UNTIL CX = 0
    
EXIT:
    MOV AH,4CH
    INT 21H 
ENDP 
END MAIN
    
    